version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:latest
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 10s
      timeout: 30s
      retries: 30
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - fastapi-toyproject-network

  app:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    healthcheck:
      test: [ "CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/api/v1')" ]
      interval: 10s
      timeout: 30s
      retries: 30
    environment:
      - RDBMS_HOST_NAME=${RDBMS_HOST_NAME}
      - RDBMS_USERNAME=${RDBMS_USERNAME}
      - RDBMS_PASSWORD=${RDBMS_PASSWORD}
      - RDBMS_DB_NAME=${RDBMS_DB_NAME}
      - REDIS_HOST_NAME=${REDIS_HOST_NAME}
      - REDIS_PORT=${REDIS_PORT}
      - RABBITMQ_HOST_NAME=${RABBITMQ_HOST_NAME}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - MONGODB_HOST_NAME=${MONGODB_HOST_NAME}
      - MONGODB_PORT=${MONGODB_PORT}
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      mysql:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    # command: >
    #   /bin/bash -c "/src/app/app_init.sh"
    volumes:
      - app_logs:/src/app/volume/log/
    networks:
      - fastapi-toyproject-network

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    environment:
      - REDIS_HOST_NAME=${REDIS_HOST_NAME}
      - REDIS_PORT=${REDIS_PORT}
      - RABBITMQ_HOST_NAME=${RABBITMQ_HOST_NAME}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - MONGODB_HOST_NAME=${MONGODB_HOST_NAME}
      - MONGODB_PORT=${MONGODB_PORT}
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      mysql:
        condition: service_healthy
      app:
        condition: service_healthy
    # command: /bin/bash -c "python celery_worker.py"
    volumes:
    networks:
      - fastapi-toyproject-network

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile.celery
    environment:
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      mysql:
        condition: service_healthy
      app:
        condition: service_healthy
      celery:
        condition: service_started
    # command: /bin/bash -c "python celery_beat.py"
    volumes:
    networks:
      - fastapi-toyproject-network

  postgresql:
    image: postgres:latest
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${RDBMS_USERNAME}" ]
      interval: 10s
      timeout: 30s
      retries: 30
    environment:
      - POSTGRES_USER=${RDBMS_USERNAME}
      - POSTGRES_PASSWORD=${RDBMS_PASSWORD}
      - POSTGRES_DB=${RDBMS_DB_NAME}
    ports:
      - "${RDBMS_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fastapi-toyproject-network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      app:
        condition: service_healthy
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx_logs:/var/log/nginx/
      - ssl_certs:/etc/nginx/certs:ro
      - certbot_www:/var/www/certbot:ro
    command: nginx -g 'daemon off;'
    networks:
      - fastapi-toyproject-network
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    volumes:
      - certbot_www:/var/www/certbot
      - ssl_certs:/etc/letsencrypt
    # entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --quiet; sleep 7d & wait $${!}; done;'"
    networks:
      - fastapi-toyproject-network
    restart: unless-stopped

  redis:
    image: redis:latest
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 30s
      retries: 30
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    networks:
      - fastapi-toyproject-network

  mongodb:
    image: mongo:latest
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 10s
      timeout: 30s
      retries: 30
    ports:
      - "${MONGODB_PORT}:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - fastapi-toyproject-network

volumes:
  postgres_data:
  mongodb_data:
  redis_data:
  rabbitmq_data:

  nginx_logs:
  app_logs:

  ssl_certs:
  certbot_www:
  
networks:
  fastapi-toyproject-network:
    driver: bridge
