FROM python:3.12-slim

WORKDIR /src

COPY ./requirements.txt /src/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /src/requirements.txt

COPY ./app_fastapi /src/app_fastapi
COPY ./app_database_redis /src/app_database_redis
COPY ./app_database_postgresql /src/app_database_postgresql
COPY ./app_database_mongodb /src/app_database_mongodb
COPY ./commons /src/commons

CMD ["python", "run_app_fastapi.py"]
