[tool.black]
line-length = 120
target-version = ['py312']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.mypy_cache
  | __pycache__
  | venv
)/
'''
skip-string-normalization = false
skip-magic-trailing-comma = false